# USE CASE: 4 Produce a Report on the Salary of Employees of a Given Role

## CHARACTERISTIC INFORMATION

### Goal in Context

As an *HR advisor* I want *to produce a report on the top N populated countries in the world, continent, region where N is provided by the user* so that *I can easily access this population information.*

### Scope

Company.

### Level

Primary task.

### Preconditions

We know the role.  Database contains Population and Demographics data.

### Success End Condition

A report is available for HR.

### Failed End Condition

No report is produced.

### Primary Actor

HR Advisor.

### Trigger

A request for Population information is sent to HR.

## MAIN SUCCESS SCENARIO

1. Marketing team has requested a countries report based on their population and the users input.
2. HR advisor captures the list of countries and their population that the campaign is targeted at.
3. HR advisor extracts the information for all the givenn countries.
4. HR advisor provides report to marketing team.

## EXTENSIONS

3. **User does not provide a valid input**:
    1. No user input or incorrect type.

4. **Language does not exist**:
	1. HR advisor informs Country does not exist.
	2. HR advisor informs Population data does not exist.

## SUB-VARIATIONS

None.

## SCHEDULE

**DUE DATE**: Release 1.0

